### ISSUE TITLE
System Status spelling errors

### ISSUE THREAD

**Issue by tony-had** [BlokasLabs/modep#6]
https://github.com/BlokasLabs/modep/blob/250dea13fc98a480fe5d79339dfc5813a5567420/scripts/modep.sh#L552-L557

**Steps To Reproduce**

1. Run modep.sh.
2. Select Tools > Check system status.

**Actual Result** 
Some instances of the word "service" are spelt as "servise".

**Expected Result**
All instances of the word "service" are spelt correctly.

**Comment by eparreno** [comment]
Fixed in that PR https://github.com/BlokasLabs/modep/pull/9

**Comment by gtrainavicius** [comment]
Thank you, merged the #9 PR.

Though in the near future, we'll be moving to sdcard image distribution instead of install scripts, as users don't really expect the install scripts to be 'taking over' the system - flashing an SD card with an OS image is more explicit. See:

- https://github.com/BlokasLabs/modep-gen
- https://community.blokas.io/t/beta-modep-2018-01-22/399/35
